### ISSUE TITLE
Two problems after upgrade to 3.5.0

### ISSUE THREAD

**Issue by abadakhshan** [akveo/nebular#1522]
After upgrade "@nebular/theme" to 3.5.0 and angular to  8, I get these errors

1.  ERROR in node_modules/@nebular/theme/components/datepicker/datepicker.directive.d.ts(3,22): error TS2307: Cannot find module '@angular/core/src/type'.

2. Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
          ^
      Expected '.
  ╷
7 │     @warn '
  │            ^
  ╵
  node_modules\@nebular\theme\styles\core\_breaking-notice.scss 7:12  root stylesheet
  node_modules\@nebular\theme\styles\_theming.scss 14:9               @import
  src\styles\themes.scss 2:9                                          @import
  stdin 5:9                                                           root stylesheet
      in E:\narik-sample\test8\node_modules\@nebular\theme\styles\core\_breaking-notice.scss (line 7, column 12)

**Comment by abadakhshan** [comment]
I see the first problem has been fixed here

https://github.com/akveo/nebular/commit/17bdb282aed6c7ba7f204b28c70f1e1cd1f5af63#diff-73913bc217784ec805f0a9f2cc16813b

**Comment by abadakhshan** [comment]
The second issue is related to this

"https://github.com/sass/dart-sass/issues/585"

**Comment by yggg** [comment]
Fixed in `3.6.0` LTS release.

**Comment by iosif-bancioiu** [comment]
The problem is still here in nebular 4.5

"dependencies": {
    "@angular/animations": "~8.2.13",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.13",
    "@angular/compiler": "~8.2.13",
    "@angular/core": "~8.2.13",
    "@angular/forms": "~8.2.13",
    "@angular/platform-browser": "~8.2.13",
    "@angular/platform-browser-dynamic": "~8.2.13",
    "@angular/router": "~8.2.13",
    "@nebular/auth": "^4.5.0",
    "@nebular/bootstrap": "^4.5.0",
    "@nebular/theme": "^4.5.0",
    "@nguniversal/express-engine": "^8.1.1",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "ionicons": "^4.6.3",
    "nebular-icons": "^1.1.0",
    "ng2-completer": "^3.0.3",
    "ng2-smart-table": "^1.5.0",
    "ngx-cookie": "^4.1.2",
    "rxjs": "~6.5.3",
    "rxjs-compat": "^6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },


--------------
Error
ERROR in ../node_modules/@nebular/theme/components/datepicker/datepicker.directive.d.ts:3:22 - error TS2307: Cannot find module '@angular/core/src/type'.

3 import { Type } from '@angular/core/src/type';
                       ~~~~~~~~~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
