### ISSUE TITLE
Strict Unary Operators

### ISSUE THREAD

**Issue by andreaslarssen** [akveo/nebular#3173]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Not 100% this is a bug, but after upgrading from 10 to 11, this warning showed up:

```
Deprecation This operation is parsed as:

    "Nebular Theme: `nb-theme()` cannot find value for key `" + $key + "` for theme `" + theming-variables.$nb-theme-name + "`"

but you may have intended it to mean:

    "Nebular Theme: `nb-theme()` cannot find value for key `" + $key + "` for theme `" + theming-variables.$nb-theme-name (+"`")

Add a space after + to clarify that it's meant to be a binary operation, or wrap
it in parentheses to make it a unary operation. This will be an error in future
versions of Sass.

More info and automated migrator: https://sass-lang.com/d/strict-unary

null

```

**Steps to reproduce:**
It seems to be triggered by theses kind of lines:
```
 color: nb-theme(some-color-variable);
```

### Other information:

**npm, node, OS, Browser**
node: v16.18.0
npm: 8.19.2
OS: Ubuntu 22.04.1 LTS 

**Angular, Nebular**
```
"@angular/core": "15.0.0",
"@nebular/date-fns": "11.0.0",
"@nebular/theme": "11.0.0",
```

**Comment by andreaslarssen** [comment]
Replaced all my usages of `nb-theme(some-color-variable)` with `var(--some-color-variable)`, and the error still persists. Only explicit function-call left to lib is `nb-install()` and `nb-theme-global()`
